apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: darts-backend:0.2
        ports:
        - containerPort: 8000
        # env:
        # - name: DB_HOST
        #   value: db-service
        # - name: DB_NAME
        #   value: myapp
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: username
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: password
